project:
  type: website
  output-dir: docs

website:
  title: "christianjmills-quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cj-mills
      - icon: twitter
        href: https://twitter.com/cdotjdotmills
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



